### ISSUE TITLE
a Caffe version issue?

### ISSUE THREAD

**Issue by xyagain** [tao-j/resnet#1]
Hi Tao

Thanks very much for your effort on implementation of paper Deep Residual Learning for Image Recognition. Recently, I am trying to repeat your implementation on our lab machine, which has installed Caffe.

I just follow your guideline as follows:
1. According to your Linux distribution, install Protocol Buffer package which includes protoc, whose version number should be 2.x. 3.x release not tested.
2. install Protocol Buffer Python package (if not shipped with protoc) by pip install protobuf.
3. Generate caffe_pb2.py file by protoc --python_out=./ --proto_path=../../caffe/src/caffe/proto/ ../../caffe/src/caffe/proto/caffe.proto, check if file is successfully generated, modify each file path accordingly.
4. Run the generator by python resnet_caffe_gen.py, and several network definition files should be generated.
5. Check the provided solver_cifar.prototxt in this directory. Modify the network definition file path in this file if necessary. mkdir snapshot, accordingly.
6. Write a script to call Caffe.

Step 1-3 is successful, but when it comes to step-4, I find there is probably something wrong with my Caffe version. With upgrading Caffe, there are many things changed in the model definition .prototxt file. For example, type: "Convolution" has been changed to type: CONVOLUTION, and so on.

I change all the different parts between old and new Caffe in the resnet_caffe_gen.py. And then I run it again, then get the following error:

Traceback (most recent call last):
  File "resnet_caffe_gen_my.py", line 159, in <module>
    pb.text_format.Merge(conv_str, _conv)
  File "build/bdist.linux-x86_64/egg/google/protobuf/text_format.py", line 265, in Merge
  File "build/bdist.linux-x86_64/egg/google/protobuf/text_format.py", line 298, in MergeLines
  File "build/bdist.linux-x86_64/egg/google/protobuf/text_format.py", line 229, in _ParseOrMerge
  File "build/bdist.linux-x86_64/egg/google/protobuf/text_format.py", line 384, in _MergeField
  File "build/bdist.linux-x86_64/egg/google/protobuf/text_format.py", line 407, in _MergeScalarField
  File "build/bdist.linux-x86_64/egg/google/protobuf/text_format.py", line 544, in Consume
google.protobuf.text_format.ParseError: 6:9 : Expected ":".

I suspect that this error is still a problem of Caffe version, but I am still not able to find the reason behind this error. Could you please give me any hints about this error. I notice that the caffe_pb2.py is already successfully generated.

Many thanks

**Comment by tao-j** [comment]
Which caffe version are you using? Could you provide a brief about your deployment environment? I only tested code with the official [caffe release](https://github.com/bvlc/caffe).

Also, please see [this prototxt file](https://github.com/BVLC/caffe/blob/master/examples/cifar10/cifar10_full_train_test.prototxt) from caffe repo. The layer type is 'Convolution' but not all in capital letters.

**Comment by tao-j** [comment]
Due to inactivity, the issue was closed. Feel free to reopen the issue.
